Feature: Forms

    Background:
        When I map page locators
            """
            Apply Now: "(//a[@href='#startups'])[1]"
            Form Panel: ".css-1bdhu2g"
            Email: "(//input[@id='email'])[1]"
            First Name: "(//input[@id='first_name'])[1]"
            Last Name: "(//input[@id='last_name'])[1]"
            Title: "(//input[@id='Title'])[1]"
            Company Name: "(//input[@id='company'])[1]"
            Company URL: "(//input[@id='company_url'])[1]"
            Company LinkedIn: "(//input[@id='crunch_angel_url'])[1]"
            Short Description: "(//textarea[@id='product_description'])[1]"
            Country: "(//button[@id='country'])[1]"
            County option: "(//span[@class='css-i2el1x'])[1]"
            Zip Postal Code: "(//input[@id='zipPostal'])[1]"
            Funding Stage: "(//button[@id='funding_stage'])[1]"
            Funding Stage option: "//span[text()='Bootstrapped']"
            Industry: "(//button[@id='industry'])[1]"
            Industry options: "//span[text()='Banks']"
            Compony AI: "(//button[@id='aiinnovator'])[1]"
            Compony AI options: "//span[text()='Yes']"
            Terms Checkbox: "[aria-label='termsCheckbox'] .css-1pic5ad"
            Submit Button: "(//button[@type='submit'])[2]"
            """
    @TC-217 @regression
    Scenario: Submit form with valid information
        Given I open site "/solutions/startups"
        When I click on the element with selector "<Apply Now>"
        Then the "<Form Panel>" visual snapshot matches "Form Panel"
        When I type the element with selector "<Email>" with "test@example.com"
        And I type the element with selector "<First Name>" with "John"
        And I type the element with selector "<Last Name>" with "Simpson"
        And I type the element with selector "<Title>" with "AQA Engineer"
        And I type the element with selector "<Company Name>" with "Best AQA inc."
        And I type the element with selector "<Company LinkedIn>" with "test.linkedin"
        And I type the element with selector "<Company URL>" with "BestAQA.inc"
        And I type the element with selector "<Short Description>" with "We provide Best AQA services"
        And I click on the element with selector "<Country>"
        And I click on the element with selector "<County option>"
        And I type the element with selector "<Zip Postal Code>" with "03-098"
        And I click on the element with selector "<Funding Stage>"
        And I click on the element with selector "<Funding Stage option>"
        And I click on the element with selector "<Industry>"
        And I click on the element with selector "<Industry options>"
        And I click on the element with selector "<Compony AI>"
        And I click on the element with selector "<Compony AI options>"
        And I click on the element with selector "<Terms Checkbox>"
        And I click on the element with selector "<Submit Button>"
        Then the "<Form Panel>" visual snapshot matches "Submited Form Panel"
